fix: command response processing issues
Unity-Technologies/go-ts3 pull request #40
Opened 2023-02-24 18:33 UTC by stevenh

Fix command response processing issues introduced by notification handling.

This includes:
* Random hangs due to writes to channels with no readers.
* Potential race when reusing client response buffer.
* Close of notify channel while handler was still running.
* Eliminated race on IsConnected check in ExecCmd.

Also:
* Use just \n for keep-alive to reduce data sent across the wire.
* Wrap more errors to improve error reporting.
* Remove io.(Reader|Writer) wrapping as that breaks scanner io.EOF handling.

2023-02-25 02:21 UTC, HalloTschuess requested changes
First of all thank you for your commitment!

I actually had something similar in mind, but I couldn't really wrap my head around it.

All goroutines seem to end now.  
Running the tests there are still random failures every few hundred tries, which I still think might have something to do with the mock server. So I wouldn't really bother with it in this pull request.

There is another thing I have noticed, which is probably not scope of this pull request:  
There is no way to find out if the connection got closed without executing a command or using `c.IsConnected()`. `c.notify` is only closed inside of `c.Close()` which has to be called manually.  
This leads to indefinitely blocking when just listening to events, without sending anything.  
From what I can tell this has been like this before as well. Exposing `c.done` might be a good way for an easy fix.

2023-02-26 13:06 UTC, stevenh commented
> First of all thank you for your commitment!
> 
> I actually had something similar in mind, but I couldn't really wrap my head around it.
> 
> All goroutines seem to end now. Running the tests there are still random failures every few hundred tries, which I still think might have something to do with the mock server. So I wouldn't really bother with it in this pull request.

Could you post the details of this, as I've not been able reproduce even with 10k runs here.

> 
> There is another thing I have noticed, which is probably not scope of this pull request: There is no way to find out if the connection got closed without executing a command or using `c.IsConnected()`. `c.notify` is only closed inside of `c.Close()` which has to be called manually. This leads to indefinitely blocking when just listening to events, without sending anything. From what I can tell this has been like this before as well. Exposing `c.done` might be a good way for an easy fix.

I've moved the close of `c.notify` into the `messageHandler` `defer` so it will now be closed as soon as a disconnect is detected. This will allow any notification consumers to know when no more notifications will be sent.

2023-02-26 23:26 UTC, HalloTschuess requested changes

2023-02-26 23:26 UTC, HalloTschuess commented on client.go
> +	// responseErrTimeout is the timeout use for sending response errors.
```suggestion
	// responseErrTimeout is the timeout used for sending response errors.
```

2023-02-26 23:26 UTC, HalloTschuess commented
> Could you post the details of this, as I've not been able reproduce even with 10k runs here.

I tried it again on a docker container running on my home docker server and even after one hour (~3.5k runs) there was not a single failure.

Maybe what I observe is some weird Windwos/WSL issue on my end, where the mockserver is not reachable sometimes.

In this instance for example it seems like the connection could not be established, as after connecting there immediately is an `EOF`
```
=== RUN   TestCmdsBasicSSH
    basic_cmds_test.go:34: 
                Error Trace:    go-ts3/basic_cmds_test.go:34
                Error:          Received unexpected error:
                                client: header: unexpected EOF
                Test:           TestCmdsBasicSSH
```

2023-02-27 19:57 UTC, HalloTschuess approved these changes
LGTM

2023-04-13 21:06 UTC, P4sca1 commented
I tried your branch and it seems to have fixed all the issues I had with connections being freezed.
Any chance that the changes can get merged into main?

2023-04-24 01:41 UTC, Mattzi commented
Can confirm this fixing all the errors. Also LGTM

Any chance this will be merged? @stevenh or @HalloTschuess

2023-04-24 06:41 UTC, stevenh commented
@danmrichards / @lwaddicor can we get this merged please

2023-04-25 00:18 UTC, lwaddicor approved these changes

2023-04-25 00:19 UTC, merged

2023-04-25 00:22 UTC, lwaddicor commented
Thanks for this, approved and merged. @stevenh do you feel a v1.1.1 or v1.2.0 is most appropriate here?

2023-04-25 08:32 UTC, stevenh commented
Thanks Lewis, as its a backwards compatible bug fix https://semver.org/ says its a patch so v1.1.1